"""Geometry and mesh handling for libertas."""

from typing import Optional, Dict, Any, Callable
from pathlib import Path
import numpy as np

try:
    from libertas.pytop import pytop as pt
except ImportError:
    from libertas import pytop as pt


class Geometry:
    """
    Unified geometry and mesh interface for topology optimization.

    Supports multiple mesh sources: pygmsh, gmsh files, FEniCS meshes,
    meshio, and fullcontrol paths.
    """

    def __init__(self, mesh: pt.Mesh, metadata: Optional[Dict[str, Any]] = None) -> None:
        """
        Initialize geometry with a FEniCS mesh.

        Args:
            mesh: FEniCS mesh object
            metadata: Optional metadata about the mesh (labels, physical groups, etc.)
        """
        self.mesh = mesh
        self.metadata = metadata or {}
        self._function_spaces: Dict[str, Any] = {}

    @classmethod
    def from_pygmsh(
        cls,
        pygmsh_mesh: Any,
        planation: bool = True,
        mpi_comm: Optional[Any] = None,
        save_path: Optional[str] = None
    ) -> "Geometry":
        """
        Create geometry from pygmsh mesh.

        Args:
            pygmsh_mesh: Mesh generated by pygmsh
            planation: Whether to apply planation
            mpi_comm: MPI communicator (default: MPI_Communicator)
            save_path: Optional path to save mesh as .xml

        Returns:
            Geometry instance
        """
        if mpi_comm is None:
            mpi_comm = pt.MPI_Communicator

        # Create directory for save_path if needed
        if save_path:
            save_path_obj = Path(save_path)
            save_path_obj.parent.mkdir(parents=True, exist_ok=True)

        mesh = pt.from_pygmsh(
            pygmsh_mesh,
            planation=planation,
            mpi_comm=mpi_comm,
            save_for=save_path
        )

        return cls(mesh, metadata={"source": "pygmsh"})

    @classmethod
    def from_file(cls, filepath: str) -> "Geometry":
        """
        Load geometry from mesh file (.xml, .xdmf, .msh).

        Args:
            filepath: Path to mesh file

        Returns:
            Geometry instance
        """
        filepath = Path(filepath)

        if not filepath.exists():
            raise FileNotFoundError(f"Mesh file not found: {filepath}")

        mesh = pt.Mesh(str(filepath))

        return cls(mesh, metadata={"source": "file", "filepath": str(filepath)})

    @classmethod
    def from_fenics(cls, fenics_mesh: pt.Mesh, metadata: Optional[Dict] = None) -> "Geometry":
        """
        Wrap existing FEniCS mesh.

        Args:
            fenics_mesh: FEniCS mesh object
            metadata: Optional metadata

        Returns:
            Geometry instance
        """
        return cls(fenics_mesh, metadata=metadata or {"source": "fenics"})

    @classmethod
    def from_meshio(cls, meshio_mesh: Any) -> "Geometry":
        """
        Create geometry from meshio mesh.

        Args:
            meshio_mesh: Mesh from meshio library

        Returns:
            Geometry instance
        """
        # Convert meshio to FEniCS format
        # This requires saving to temp file and loading
        import tempfile

        with tempfile.NamedTemporaryFile(suffix=".xdmf", delete=False) as tmp:
            tmp_path = tmp.name

        try:
            import meshio
            meshio.write(tmp_path, meshio_mesh)
            mesh = pt.Mesh(tmp_path)
        finally:
            Path(tmp_path).unlink(missing_ok=True)
            Path(tmp_path.replace(".xdmf", ".h5")).unlink(missing_ok=True)

        return cls(mesh, metadata={"source": "meshio"})

    @classmethod
    def from_fullcontrol(
        cls,
        fc_steps: list,
        extrusion_width: float = 0.4,
        layer_height: float = 0.2,
        mesh_size: float = 0.1
    ) -> "Geometry":
        """
        Create geometry from fullcontrol printing path.

        Converts 3D printing toolpath into a mesh for topology optimization.

        Args:
            fc_steps: List of fullcontrol Points/steps
            extrusion_width: Width of extruded material
            layer_height: Height of each layer
            mesh_size: Mesh element size

        Returns:
            Geometry instance
        """
        # This is a placeholder - full implementation would:
        # 1. Extract path coordinates from fc_steps
        # 2. Create swept volume geometry
        # 3. Generate mesh using pygmsh or gmsh

        raise NotImplementedError(
            "fullcontrol path conversion not yet implemented. "
            "This feature requires path-to-volume conversion logic."
        )

    @classmethod
    def rectangle(
        cls,
        width: float,
        height: float,
        mesh_size: float = 0.1,
        origin: tuple = (0.0, 0.0)
    ) -> "Geometry":
        """
        Create rectangular geometry (convenience method).

        Args:
            width: Width of rectangle
            height: Height of rectangle
            mesh_size: Mesh element size
            origin: Origin point (x, y)

        Returns:
            Geometry instance
        """
        nx = max(int(width / mesh_size), 2)
        ny = max(int(height / mesh_size), 2)

        mesh = pt.RectangleMesh(
            pt.MPI_Communicator.comm_world,
            pt.Point(origin[0], origin[1]),
            pt.Point(origin[0] + width, origin[1] + height),
            nx, ny
        )

        return cls(
            mesh,
            metadata={
                "source": "builtin",
                "shape": "rectangle",
                "width": width,
                "height": height
            }
        )

    @classmethod
    def box(
        cls,
        width: float,
        height: float,
        depth: float,
        mesh_size: float = 0.1,
        origin: tuple = (0.0, 0.0, 0.0)
    ) -> "Geometry":
        """
        Create box geometry (convenience method).

        Args:
            width: Width of box (x)
            height: Height of box (y)
            depth: Depth of box (z)
            mesh_size: Mesh element size
            origin: Origin point (x, y, z)

        Returns:
            Geometry instance
        """
        nx = max(int(width / mesh_size), 2)
        ny = max(int(height / mesh_size), 2)
        nz = max(int(depth / mesh_size), 2)

        mesh = pt.BoxMesh(
            pt.MPI_Communicator.comm_world,
            pt.Point(origin[0], origin[1], origin[2]),
            pt.Point(origin[0] + width, origin[1] + height, origin[2] + depth),
            nx, ny, nz
        )

        return cls(
            mesh,
            metadata={
                "source": "builtin",
                "shape": "box",
                "width": width,
                "height": height,
                "depth": depth
            }
        )

    def get_function_space(self, family: str, degree: int, vector: bool = False, dim: Optional[int] = None) -> Any:
        """
        Get or create function space on this mesh.

        Args:
            family: Element family (e.g., "CG", "DG")
            degree: Polynomial degree
            vector: Whether to create vector function space
            dim: Vector dimension (for vector spaces)

        Returns:
            FEniCS function space
        """
        key = f"{family}_{degree}_{'vector' if vector else 'scalar'}_{dim or ''}"

        if key not in self._function_spaces:
            if vector:
                if dim:
                    self._function_spaces[key] = pt.VectorFunctionSpace(
                        self.mesh, family, degree, dim=dim
                    )
                else:
                    self._function_spaces[key] = pt.VectorFunctionSpace(
                        self.mesh, family, degree
                    )
            else:
                self._function_spaces[key] = pt.FunctionSpace(self.mesh, family, degree)

        return self._function_spaces[key]

    def get_tensor_function_space(self, family: str, degree: int) -> Any:
        """
        Get or create tensor function space on this mesh.

        Args:
            family: Element family (e.g., "CG", "DG")
            degree: Polynomial degree

        Returns:
            FEniCS tensor function space
        """
        key = f"{family}_{degree}_tensor"

        if key not in self._function_spaces:
            self._function_spaces[key] = pt.TensorFunctionSpace(self.mesh, family, degree)

        return self._function_spaces[key]

    @property
    def dim(self) -> int:
        """Get spatial dimension of the geometry."""
        return self.mesh.geometry().dim()

    def save(self, filepath: str) -> None:
        """
        Save mesh to file.

        Args:
            filepath: Output file path (.xml, .xdmf)
        """
        filepath = Path(filepath)

        if filepath.suffix == ".xml":
            pt.File(str(filepath)) << self.mesh
        elif filepath.suffix == ".xdmf":
            pt.XDMFFile(str(filepath)).write(self.mesh)
        else:
            raise ValueError(f"Unsupported file format: {filepath.suffix}")
